# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('star_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('star_day', models.DateField(blank=True, null=True)),
                ('end_day', models.DateField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('is_all_day', models.BooleanField(default=False)),
                ('repeats', models.CharField(blank=True, choices=[('1', 'Weekly'), ('2', 'Monthly'), ('3', 'Yearly')], max_length=2, null=True)),
                ('every', models.IntegerField(blank=True, null=True)),
                ('location', models.TextField()),
                ('is_reserve', models.BooleanField(default=False)),
                ('is_pay', models.BooleanField(default=False)),
                ('is_call_bussiness', models.BooleanField(default=False)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('quantily_number', models.FloatField(blank=True, null=True)),
                ('botton_label', models.CharField(blank=True, choices=[('1', 'Donate'), ('2', 'Tithe')], max_length=2, null=True)),
                ('is_visibility', models.BooleanField(default=True)),
                ('is_schedule_required', models.BooleanField(default=True)),
                ('is_documentation_required', models.BooleanField(default=True)),
                ('is_digital_signature', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('auto_check_in', models.BooleanField(default=True)),
                ('assignee_type', models.CharField(blank=True, choices=[('1', 'Instructor'), ('2', 'Troinor'), ('3', 'Umpire'), ('4', 'Baby Sitter')], max_length=2, null=True)),
                ('assignee_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Activity',
            },
        ),
    ]
